name: tekartik_idb_playground
description: idb_shim playground
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  web:
  sembast:
  path: ">=1.9.0"
  idb_shim: ">=2.6.5+1"
  idb_sqflite: ">=1.3.6-1"
  sqflite_common_ffi: ">=2.3.4"
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_dev_menu
  idb_test:
    git:
      url: https://github.com/tekartik/idb_shim.dart
      path: idb_test
    version: '>=0.3.3'
dev_dependencies:
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  lints: ">=5.0.0"
  sembast_test:
    git:
      url: https://github.com/tekartik/sembast.dart
      path: sembast_test
resolution: workspace
