name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - packages/idb_playground
  - packages/idb_provider
  - packages/idb_shim_html_compat
  - packages/idb_shim_web_worker_exp
  - packages/sdb_shim_web_worker_exp
  - packages/sembast_web_html_compat
