name: idb_shim_html_compat
version: 2.4.1+4
description: indexed_db dart base interface with implementation for native (browser), file (io) and in memory.
homepage: https://github.com/tekartik/idb_shim.dart/tree/master/idb_shim
topics:
  - nosql
  - database

environment:
  sdk: ^3.9.0

dependencies:
  sembast: ">=3.7.4+3"
  collection: ">=1.18.0"
  path: ">=1.9.0"
  js: '>=0.6.3 <2.0.0'
  meta: ">=1.15.0"
  web: '>=0.5.0 <2.0.0'
  idb_shim: '>=2.7.1-2 <4.0.0'

dev_dependencies:
  pub_semver: ">=2.1.4"
  stack_trace: '>=1.10.0'
  logging: '>=1.0.0'
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  build_runner: ">=2.4.13"
  build_test: '>=1.3.7'
  build_web_compilers: ">=4.0.11"
  yaml: ">=3.1.2"
  lints: ">=5.0.0"
resolution: workspace

